config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :events
  resources :contacts
  resources :image_sliders
  resources :sliders
  resources :articles
  root 'pages#home'

  get 'app' => "app#index"
  get 'participants' => 'pages#participants', as: :all_participants
  get '/list-participant' => 'participants#index', as: :list_participants
  get '/news' => 'pages#news', as: :all_news
  get '/contact-us' => 'pages#contact', as: :create_contact
  get 'get-involved' => "pages#getinvolved", as: :getinvolved
  get 'say-yes-to-less-activity' => "pages#events", as: :list_event

  resources :participants do
    collection { post :import }
  end

  resources :pages
  resources :users
  resources :setups
  devise_for :users,
  path:'user',
  path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }
  # get '/participants'=> 'pages#participants', as: :participants
  get '/:id', to: 'pages#show', as: :pages_show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title

  belongs_to :category
  belongs_to :slider, optional: true

  mount_uploader :image, ImageUploader

  Status = [ :publish, :draft, :trash ]

  class << self
    def news
      Article.where(category_id: 1)
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord


    has_many :children, :class_name => "Category", :foreign_key => :parent_id
    belongs_to :parent, :class_name => "Category", :foreign_key => :parent_id, optional: true


end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord

  extend FriendlyId
  friendly_id :title

  mount_uploader :image, ImageUploader

end

app/models/image_slider.rb
class ImageSlider < ApplicationRecord


  mount_uploader :image, ImageUploader
  belongs_to :slider
end

app/models/page.rb
class Page < ApplicationRecord
  extend FriendlyId
  friendly_id :title

  validates :title, presence: true
end

app/models/participant.rb
class Participant < ApplicationRecord

  Type = [ 'standalone', 'hotel-restaurant', 'hotel' ]

  class << self
    def standalone
      Participant.where(participant_type: "standalone")
    end

    def hotel_restaurant
      Participant.where(participant_type: "hotel-restaurant")
    end

    def hotel
      Participant.where(participant_type: "hotel")
    end
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      new
      params =
      {participant:
        {
          name: row["title"],
          participant_type: row["type"]
        }
       }
        Participant.create(params[:participant])
      end
    end

    def self.open_spreadsheet(file)
      case File.extname(file.original_filename)
      when '.csv' then Roo::CSV.new(file.path,file_warning: :ignore)
      when '.xls' then Roo::Excel.new(file.path,file_warning: :ignore)
      when '.xlsx' then Roo::Excelx.new(file.path,file_warning: :ignore)
      else raise "Unknown file type: #{file.original_filename}"
      end
    end

end

app/models/setup.rb
class Setup < ApplicationRecord
  mount_uploader :site_image, LogoUploader
  mount_uploader :site_favicon, IconUploader
  validates :site_name, presence: true
  validates :site_title, presence: true
  validates :site_url, presence: true
end

app/models/slider.rb
class Slider < ApplicationRecord
  has_many :image_sliders, inverse_of: :slider
  accepts_nested_attributes_for :image_sliders, reject_if: :all_blank, allow_destroy: true

  mount_uploader :cover, ImageUploader

  Type = ["Homepage", "Article"]

  class << self
    def article
      Slider.where(slider_type: "Article")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend FriendlyId
  friendly_id :username
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :username, presence: true
  validates :role, presence: true
  validates :email, presence: true

  mount_uploader :avatar, AvatarUploader

  ROLES = {root:'root',administrator:'administrator',author:'author', editor:'editor'}
  scope :root, -> {where(role: ROLES[:root])}
  scope :administrator, -> {where(role: ROLES[:administrator])}
  scope :author, -> {where(role: ROLES[:author])}
  scope :editor, -> {where(role: ROLES[:editor])}
  def is_root?
    self.role == ROLES[:root]
  end
  def is_administrator?
    self.role == ROLES[:administrator]
  end
  def is_author?
    self.role == ROLES[:author]
  end
  def is_editor?
    self.role == ROLES[:editor]
  end
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  before_action :authenticate_user!
  layout 'admin'
  def index
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :edit, :new]
  layout 'admin', only: [:index, :edit, :new]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @latest = Article.where.not(id: @article.id).where(category_id: @article.category_id)
  end

  # GET /articles/new
  def new
    @article = Article.new(publish: DateTime.now)
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :meta_description, :slug, :content, :image, :publish, :category_id, :status, :slider_id)
    end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_link(link_text, link_path)
  class_name = current_page?(link_path) ? 'nav-item active' : 'nav-item'

    content_tag(:li, :class => class_name) do
    link_to link_text, link_path, class:"nav-link"
    end
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/setups_helper.rb
module SetupsHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => "form-horizontal article" } do |f| %>

  <% if @article.errors.any? %>
  <div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h3>
    </div>
    <div class="panel-body">
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <% end %>

  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <div class="form-group">
            <%= f.label :title, :class => 'control-label' %>
            <%= f.text_field :title, :class => 'form-control' %>
            <%=f.error_span(:title) %>
          </div>
          <% if @article.new_record? %>

          <div class="form-group">
            <%= f.label :meta_description, :class => 'control-label' %>
            <%= f.text_area :meta_description, maxlength:"230", rows:8, :class => 'form-control' %>
            <%=f.error_span(:meta_description) %>
          </div>
          <% else %>
          <div class="form-group">
            <%= f.label :meta_description, maxlength:"230", :class => 'control-label' %>
            <%= f.text_area :meta_description, maxlength:"230", rows:4, :class => 'form-control' %>
            <%=f.error_span(:meta_description) %>
          </div>
          <div class="form-group">
            <%= f.label :slug, :class => 'control-label' %>
            <%= f.text_field :slug, :class => 'form-control' %>
            <%=f.error_span(:slug) %>
          </div>

          <% end %>

        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card">
        <div class="card-body">
          <%= f.label :image, :class => 'control-label' %>
          <% if @article.image.nil? || @article.image.blank? %>
          <%= f.file_field :image, class: "dropify", 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-max-file-size'=>'1M', 'data-show-remove'=>'false', 'data-height' => '260' %>
          <% else %>
          <%= f.file_field :image, class: "dropify", 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-max-file-size'=>'1M', 'data-show-remove'=>'false', 'data-height' => '260', 'data-default-file' => @article.image.url %>
          <% end %>
          <%=f.error_span(:image) %>
        </div>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-body">
      <div class="row">
        <div class="col-md-3">
          <div class="form-group">
            <%= f.label :publish, :class => 'control-label' %>
            <% if @article.new_record? %>
              <%= f.datetime_field :publish, :class => 'form-control' %>
                <% else %>
              <%= f.datetime_field :publish, :class => 'form-control' %>
            <% end %>
            <%=f.error_span(:publish) %>
          </div>
        </div>
        <div class="col-md-3">
          <div class="form-group">
            <%= f.label :status, :class => 'control-label' %>
            <%= f.select :status, Article::Status.map {|s| [s ]},{:include_blank => '-Choose-'} , :class=>"form-control w-100 ", :placeholder=>"select", style: 'height:40px;', required: true%>
            <%=f.error_span(:status) %>
          </div>
        </div>
        <div class="col-md-3">
          <div class="form-group">
            <%= f.label :category_id, :class => 'control-label' %>
            <%= f.select :category_id, Category.all.map {|s| [s.title, s.id ]},{:include_blank => '-Choose-'}, :class=>"form-control w-100 select2"%>
            <%=f.error_span(:category_id) %>
          </div>
        </div>
        <div class="col-md-3">
          <div class="form-group">
            <%= f.label :slider_id,"Add Slider", :class => 'control-label' %>
            <%= f.select :slider_id, Slider.article.map {|s| [s.title, s.id ]},{:include_blank => '-Choose-'}, :class=>"form-control w-100 select2"%>
            <%=f.error_span(:slider_id) %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-body">
      <div class="form-group">
        <%= f.label :content, :class => 'control-label' %>
        <%= f.cktext_area :content, :class => 'form-control',:ckeditor => {:removePlugins => 'forms'} %>
        <%=f.error_span(:content) %>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-body">
      <div class="form-group text-center mb-0">
          <%= f.submit nil, :class => 'btn btn-primary' %>
          <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
          articles_path, :class => 'btn btn-default' %>
      </div>
    </div>
  </div>



  <% end %>

app/views/articles/edit.html.erb
<%- model_class = Article -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= pages_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.new', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/articles/index.html.erb
<%- model_class = Article -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <%= link_to t('.new', :default => t("helpers.links.new")), new_article_path, :class => 'btn btn-success mb-2' %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:id) %></th>
                <th><%= model_class.human_attribute_name(:title) %></th>
                <th><%= model_class.human_attribute_name(:category) %></th>
                <th><%= model_class.human_attribute_name(:status) %></th>
                <th><%= model_class.human_attribute_name(:publish) %></th>
                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @articles.each do |article| %>
              <tr>
                <td><%= link_to article.id, article_path(article) %></td>
                <td><%= article.title %></td>
                <td><%= article.category.title rescue "-" %></td>
                <td><%= article.status %></td>
                <td><%= article.publish.strftime("%Y/%m/%d @%H:%M") rescue "-"  %></td>
                <td>
                  <%= link_to t('.show', :default => t("helpers.links.show")),
                  article_path(article), :class => 'btn btn-default btn-xs' %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_article_path(article), :class => 'btn btn-default btn-xs' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  article_path(article),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-xs btn-danger' %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function() {
  $(".table").dataTable();
});
</script>

app/views/articles/new.html.erb
<%- model_class = Article -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= pages_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/articles/show.html.erb
<section>
  <div class="container">
    <div class="row justify-content-between">
      <div class="col-md-8 article">
        <p class="text-green"><%= @article.category.title %>  </p>
        <h1><%= @article.title %></h1>
        <div class="date text-green my-3 d-flex justify-content-between">
          <p><i><%= @article.publish.strftime("%e %B %Y") rescue "-" %></i></p>
        </div>
        <% if @article.slider != nil %>
        <div class="mb-3">
          <div class="row m-0">
          <% @article.slider.image_sliders.each do |x| %>
          <div class="col-md-4 p-1 mb-1">
            <a href="<%= x.image %>" class="d-block popupbanner" data-lightbox="zoom-banner">
              <img src="<%= x.image %>" alt="<%= @article.title %>" class="w-100" >
            </a>
          </div>
          <% end %>
          </div>
        </div>
        <% end %>
        <%= @article.content.html_safe %>
      </div>
      <div class="col-md-3 py-3 bg-gray show">
        <div class="mb-3">
          <p class="text-green" style="font-size: 25px;font-weight: 900;" >
            Latest News
          </p>
          <div class=" p-3 bg-white mb-3 shadow-sm">
            <ul class="list-unstyled listed">
              <% @latest.each do |x| %>
              <li>
                <a href="<%= article_path(x.slug) %>">
                  <%= x.title %>
                </a>
              </li>
              <% end %>
            </ul>
          </div>
        </div>

        <div class="sticky-top" style="top:100px;  z-index:0">
          <div class="mb-3" >
            <p class="text-green" style="font-size: 25px;font-weight: 900;" >
              Upcoming Events
            </p>
            <div class=" p-3 bg-white mb-3 shadow-sm">
              <a href="#">
                <div class="d-block">
                  <p style="font-size:18px;font-weight:600;" class="mb-2">
                    MVB EXPO 2019
                  </p>
                  <p class="mb-0">
                    3 - 12 December 2019
                  </p>
                  <div class="d-block">
                    <i class="fa fa-map-marker mr-1 text-green" aria-hidden="true"></i> <span>Sultan Jakarta</span>
                  </div>
                </div>

              </a>

            </div>

          </div>

          <div class="bg-success p-3 mb-3 shadow-sm sticky-top" style="border-width:2px !important; top:100px;">
            <form id="ema_signup_form_1" target="_blank" action="https://madmimi.com/signups/subscribe/26e055805c584b5693c7788c648b7ba8" accept-charset="UTF-8" method="post">
              <input name="utf8" type="hidden" value="✓">
              <p style="font-size: 25px;font-weight: 900; color:white;" >
                Get Closer To Us<span class="text-green">.</span>
              </p>
              <div class="">
                <div class="  input-group">
                  <input id="signup_email" name="signup[email]" class="mm-field required email mb-3 w-100 enews" type="text" data-required-field="This field is required" placeholder="your email" style="">
                  <button type="submit" name="button" class="btn btn-light w-100">SUBMIT</button>
                </div>
              </div>
            </form>
          </div>

        </div>



      </div>
    </div>
  </div>
</section>