config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :events
  resources :contacts
  resources :image_sliders
  resources :sliders
  resources :articles
  root 'pages#home'

  get 'app' => "app#index"
  get 'participants' => 'pages#participants', as: :all_participants
  get '/list-participant' => 'participants#index', as: :list_participants
  get '/news' => 'pages#news', as: :all_news
  get '/contact-us' => 'pages#contact', as: :create_contact
  get 'get-involved' => "pages#getinvolved", as: :getinvolved
  get 'say-yes-to-less-activity' => "pages#events", as: :list_event

  resources :participants do
    collection { post :import }
  end

  resources :pages
  resources :users
  resources :setups
  devise_for :users,
  path:'user',
  path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }
  # get '/participants'=> 'pages#participants', as: :participants
  get '/:id', to: 'pages#show', as: :pages_show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title

  belongs_to :category
  belongs_to :slider, optional: true

  mount_uploader :image, ImageUploader

  Status = [ :publish, :draft, :trash ]

  class << self
    def news
      Article.where(category_id: 1)
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord


    has_many :children, :class_name => "Category", :foreign_key => :parent_id
    belongs_to :parent, :class_name => "Category", :foreign_key => :parent_id, optional: true


end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord

  extend FriendlyId
  friendly_id :title

  mount_uploader :image, ImageUploader

end

app/models/image_slider.rb
class ImageSlider < ApplicationRecord


  mount_uploader :image, ImageUploader
  belongs_to :slider
end

app/models/page.rb
class Page < ApplicationRecord
  extend FriendlyId
  friendly_id :title

  validates :title, presence: true
end

app/models/participant.rb
class Participant < ApplicationRecord

  Type = [ 'standalone', 'hotel-restaurant', 'hotel' ]

  class << self
    def standalone
      Participant.where(participant_type: "standalone")
    end

    def hotel_restaurant
      Participant.where(participant_type: "hotel-restaurant")
    end

    def hotel
      Participant.where(participant_type: "hotel")
    end
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      new
      params =
      {participant:
        {
          name: row["title"],
          participant_type: row["type"]
        }
       }
        Participant.create(params[:participant])
      end
    end

    def self.open_spreadsheet(file)
      case File.extname(file.original_filename)
      when '.csv' then Roo::CSV.new(file.path,file_warning: :ignore)
      when '.xls' then Roo::Excel.new(file.path,file_warning: :ignore)
      when '.xlsx' then Roo::Excelx.new(file.path,file_warning: :ignore)
      else raise "Unknown file type: #{file.original_filename}"
      end
    end

end

app/models/setup.rb
class Setup < ApplicationRecord
  mount_uploader :site_image, LogoUploader
  mount_uploader :site_favicon, IconUploader
  validates :site_name, presence: true
  validates :site_title, presence: true
  validates :site_url, presence: true
end

app/models/slider.rb
class Slider < ApplicationRecord
  has_many :image_sliders, inverse_of: :slider
  accepts_nested_attributes_for :image_sliders, reject_if: :all_blank, allow_destroy: true

  mount_uploader :cover, ImageUploader

  Type = ["Homepage", "Article"]

  class << self
    def article
      Slider.where(slider_type: "Article")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend FriendlyId
  friendly_id :username
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :username, presence: true
  validates :role, presence: true
  validates :email, presence: true

  mount_uploader :avatar, AvatarUploader

  ROLES = {root:'root',administrator:'administrator',author:'author', editor:'editor'}
  scope :root, -> {where(role: ROLES[:root])}
  scope :administrator, -> {where(role: ROLES[:administrator])}
  scope :author, -> {where(role: ROLES[:author])}
  scope :editor, -> {where(role: ROLES[:editor])}
  def is_root?
    self.role == ROLES[:root]
  end
  def is_administrator?
    self.role == ROLES[:administrator]
  end
  def is_author?
    self.role == ROLES[:author]
  end
  def is_editor?
    self.role == ROLES[:editor]
  end
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  before_action :authenticate_user!
  layout 'admin'
  def index
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, execpt: :show
  layout 'admin', execpt: :show
  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to participants_path, notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to participants_path, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Participant.import(params[:file])
    redirect_to participants_url, notice: "Participant imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:overview, :name, :website, :participant_type, :building_name, :street_name, :region, :city, :province, :phone_number, :ig_account, :ig_link, :facebook_account, :facebook_link, :email, :map, :lat, :long, :image, :postal_code, :logo)
    end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/setups_helper.rb
module SetupsHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/participants/_form.html.erb
<%= form_for @participant, :html => { :class => "form-horizontal participant" } do |f| %>

<% if @participant.errors.any? %>
<div id="error_expl" class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title"><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h3>
  </div>
  <div class="panel-body">
    <ul>
      <% @participant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<div class="row align-items-center">
  <div class="col-md-8">
    <div class="card">
      <div class="card-body">
        <div class="form-group">
          <%= f.label :name, :class => 'control-label' %>
          <%= f.text_field :name, :class => 'form-control' %>
          <%=f.error_span(:name) %>
        </div>
        <div class="form-group">
          <%= f.label :building_name, :class => 'control-label' %>
          <%= f.text_field :building_name, :class => 'form-control' %>
          <%=f.error_span(:building_name) %>
        </div>
        <div class="form-group">
          <%= f.label :street_name, :class => 'control-label' %>
          <%= f.text_area :street_name, rows:6, :class => 'form-control' %>
          <%=f.error_span(:street_name) %>
        </div>
        <div class="form-group">
          <%= f.label :region, :class => 'control-label' %>
          <%= f.text_field :region, :class => 'form-control' %>
          <%=f.error_span(:region) %>
        </div>
        <div class="form-group">
          <%= f.label :city, :class => 'control-label' %>
          <%= f.text_field :city, :class => 'form-control' %>
          <%=f.error_span(:city) %>
        </div>
        <div class="form-group">
          <%= f.label :postal_code, :class => 'control-label' %>
          <%= f.text_field :postal_code, :class => 'form-control' %>
          <%=f.error_span(:postal_code) %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <div class="form-group">
          <%= f.label :image, :class => 'control-label' %>
          <% if @participant.image.nil? || @participant.image.blank? %>
          <%= f.file_field :image, class: "dropify", 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-max-file-size'=>'1M', 'data-show-remove'=>'false', 'data-height' => '200' %>
          <% else %>
          <%= f.file_field :image, class: "dropify", 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-max-file-size'=>'1M', 'data-show-remove'=>'false', 'data-height' => '200', 'data-default-file' => @participant.image.url %>
          <% end %>
          <%=f.error_span(:image) %>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <div class="form-group">
          <%= f.label :logo, :class => 'control-label' %>
          <% if @participant.logo.nil? || @participant.logo.blank? %>
          <%= f.file_field :logo, class: "dropify", 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-max-file-size'=>'1M', 'data-show-remove'=>'false', 'data-height' => '200' %>
          <% else %>
          <%= f.file_field :logo, class: "dropify", 'data-allowed-file-extensions'=>'jpg jpeg png', 'data-max-file-size'=>'1M', 'data-show-remove'=>'false', 'data-height' => '200', 'data-default-file' => @participant.logo.url %>
          <% end %>
          <%=f.error_span(:logo) %>
        </div>
      </div>
    </div>
  </div>
</div>



<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-md-4">
        <div class="form-group">
          <%= f.label :email, :class => 'control-label' %>
          <%= f.text_field :email, :class => 'form-control' %>
          <%=f.error_span(:email) %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="form-group">
          <%= f.label :website, :class => 'control-label' %>
          <%= f.text_field :website, :class => 'form-control' %>
          <%=f.error_span(:website) %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="form-group">
          <%= f.label :phone_number, :class => 'control-label' %>
          <%= f.text_field :phone_number, :class => 'form-control' %>
          <%=f.error_span(:phone_number) %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :ig_account, :class => 'control-label' %>
          <%= f.text_field :ig_account, :class => 'form-control' %>
          <%=f.error_span(:ig_account) %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :ig_link, :class => 'control-label' %>
          <%= f.text_field :ig_link, :class => 'form-control' %>
          <%=f.error_span(:ig_link) %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :facebook_account, :class => 'control-label' %>
          <%= f.text_field :facebook_account, :class => 'form-control' %>
          <%=f.error_span(:facebook_account) %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :facebook_link, :class => 'control-label' %>
          <%= f.text_field :facebook_link, :class => 'form-control' %>
          <%=f.error_span(:facebook_link) %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-body">

    <div class="row">
      <div class="col-12">
        <div class="form-group">
          <%= f.label :map, :class => 'control-label' %>
          <%= f.text_area :map, :class => 'form-control',rows: 3 %>
          <%=f.error_span(:map) %>
        </div>
      </div>
      <div class="col-6">
        <div class="form-group">
          <%= f.label :lat, :class => 'control-label' %>
          <%= f.text_field :lat, :class => 'form-control' %>
          <%=f.error_span(:lat) %>
        </div>
      </div>
      <div class="col-6">
        <div class="form-group">
          <%= f.label :long, :class => 'control-label' %>
          <%= f.text_field :long, :class => 'form-control' %>
          <%=f.error_span(:long) %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-body" style="padding: 2rem !important;">
    <div class="form-group">
      <%= f.cktext_area :overview, :class => 'form-control',:ckeditor => {:removePlugins => 'forms'} %>
      <%=f.error_span(:overview) %>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <div class="form-group">
      <div class="text-center">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
        participants_path, :class => 'btn btn-default' %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/participants/edit.html.erb
<%- model_class = Participant -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= pages_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.new', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">

      <%= render :partial => 'form' %>

</div>

app/views/participants/index.html.erb
<%- model_class = Participant -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <%= link_to t('.new', :default => t("helpers.links.new")), new_participant_path, :class => 'btn btn-success mb-2' %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:id) %></th>
                <th><%= model_class.human_attribute_name(:name) %></th>
                <th><%= model_class.human_attribute_name(:website) %></th>
                <th><%= model_class.human_attribute_name(:participant_type) %></th>
                <th><%= model_class.human_attribute_name(:created_at) %></th>
                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @participants.each do |participant| %>
              <tr>
                <td><%= link_to participant.id, participant_path(participant) %></td>
                <td><%= participant.name %></td>
                <td><%= participant.website %></td>
                <td><%= participant.participant_type %></td>
                <td><%=l participant.created_at %></td>
                <td>
                  <%= link_to t('.show', :default => t("helpers.links.show")),
                  participant_path(participant), :class => 'btn btn-default btn-xs' %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_participant_path(participant), :class => 'btn btn-default btn-xs' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  participant_path(participant),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-xs btn-danger' %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h3 class="mb-2">Import Data</h3>
          <%= form_tag import_participants_path, multipart: true do %>
            <div class="input-group">
              <div class="custom-file">
                <%= file_field_tag :file %>
              </div>
              <div class="input-group-append">
                <%= submit_tag "Upload", class:'btn btn-success' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function() {
  $(".table").dataTable();
});
</script>

app/views/participants/new.html.erb
<%- model_class = Participant -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= pages_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">

      <%= render :partial => 'form' %>

</div>

app/views/participants/show.html.erb
<%- model_class = Participant -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @participant.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:website) %>:</strong></dt>
  <dd><%= @participant.website %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type) %>:</strong></dt>
  <dd><%= @participant.participant_type %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              participants_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_participant_path(@participant), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              participant_path(@participant),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>