config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :events
  resources :contacts
  resources :image_sliders
  resources :sliders
  resources :articles
  root 'pages#home'

  get 'app' => "app#index"
  get 'participants' => 'pages#participants', as: :all_participants
  get '/list-participant' => 'participants#index', as: :list_participants
  get '/news' => 'pages#news', as: :all_news
  get '/contact-us' => 'pages#contact', as: :create_contact
  get 'get-involved' => "pages#getinvolved", as: :getinvolved
  get 'say-yes-to-less-activity' => "pages#events", as: :list_event

  resources :participants do
    collection { post :import }
  end

  resources :pages
  resources :users
  resources :setups
  devise_for :users,
  path:'user',
  path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }
  # get '/participants'=> 'pages#participants', as: :participants
  get '/:id', to: 'pages#show', as: :pages_show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title

  belongs_to :category
  belongs_to :slider, optional: true

  mount_uploader :image, ImageUploader

  Status = [ :publish, :draft, :trash ]

  class << self
    def news
      Article.where(category_id: 1)
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord


    has_many :children, :class_name => "Category", :foreign_key => :parent_id
    belongs_to :parent, :class_name => "Category", :foreign_key => :parent_id, optional: true


end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord

  extend FriendlyId
  friendly_id :title

  mount_uploader :image, ImageUploader

end

app/models/image_slider.rb
class ImageSlider < ApplicationRecord


  mount_uploader :image, ImageUploader
  belongs_to :slider
end

app/models/page.rb
class Page < ApplicationRecord
  extend FriendlyId
  friendly_id :title

  validates :title, presence: true
end

app/models/participant.rb
class Participant < ApplicationRecord

  Type = [ 'standalone', 'hotel-restaurant', 'hotel' ]

  class << self
    def standalone
      Participant.where(participant_type: "standalone")
    end

    def hotel_restaurant
      Participant.where(participant_type: "hotel-restaurant")
    end

    def hotel
      Participant.where(participant_type: "hotel")
    end
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      new
      params =
      {participant:
        {
          name: row["title"],
          participant_type: row["type"]
        }
       }
        Participant.create(params[:participant])
      end
    end

    def self.open_spreadsheet(file)
      case File.extname(file.original_filename)
      when '.csv' then Roo::CSV.new(file.path,file_warning: :ignore)
      when '.xls' then Roo::Excel.new(file.path,file_warning: :ignore)
      when '.xlsx' then Roo::Excelx.new(file.path,file_warning: :ignore)
      else raise "Unknown file type: #{file.original_filename}"
      end
    end

end

app/models/setup.rb
class Setup < ApplicationRecord
  mount_uploader :site_image, LogoUploader
  mount_uploader :site_favicon, IconUploader
  validates :site_name, presence: true
  validates :site_title, presence: true
  validates :site_url, presence: true
end

app/models/slider.rb
class Slider < ApplicationRecord
  has_many :image_sliders, inverse_of: :slider
  accepts_nested_attributes_for :image_sliders, reject_if: :all_blank, allow_destroy: true

  mount_uploader :cover, ImageUploader

  Type = ["Homepage", "Article"]

  class << self
    def article
      Slider.where(slider_type: "Article")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend FriendlyId
  friendly_id :username
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :username, presence: true
  validates :role, presence: true
  validates :email, presence: true

  mount_uploader :avatar, AvatarUploader

  ROLES = {root:'root',administrator:'administrator',author:'author', editor:'editor'}
  scope :root, -> {where(role: ROLES[:root])}
  scope :administrator, -> {where(role: ROLES[:administrator])}
  scope :author, -> {where(role: ROLES[:author])}
  scope :editor, -> {where(role: ROLES[:editor])}
  def is_root?
    self.role == ROLES[:root]
  end
  def is_administrator?
    self.role == ROLES[:administrator]
  end
  def is_author?
    self.role == ROLES[:author]
  end
  def is_editor?
    self.role == ROLES[:editor]
  end
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  before_action :authenticate_user!
  layout 'admin'
  def index
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :edit, :new]
layout 'admin', only: [:index, :edit, :new]
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :meta_description, :slug, :parent_id)
    end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_link(link_text, link_path)
  class_name = current_page?(link_path) ? 'nav-item active' : 'nav-item'

    content_tag(:li, :class => class_name) do
    link_to link_text, link_path, class:"nav-link"
    end
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/setups_helper.rb
module SetupsHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<div class="row">
  <% if @category.errors.any? %>
    <div class="col-md-12">
      <div id="error_expl" class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h3>
        </div>
        <div class="panel-body">
          <ul>
            <% @category.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
</div>
<%= form_for @category, :html => { :class => "form-horizontal category" } do |f| %>
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.label :title, :class => 'control-label' %>
                <%= f.text_field :title, :class => 'form-control', required:true %>
                <%=f.error_span(:title) %>
              </div>
            </div>
          </div>
          <% unless @category.new_record? %>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.label :slug, :class => 'control-label' %>
                <%= f.text_field :slug, :class => 'form-control', required:true %>
                <%=f.error_span(:slug) %>
              </div>
            </div>
          </div>
          <% end %>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.label :parent_id, :class => 'control-label' %>
                <%= f.select :parent_id, Category.all.map {|s| [s.title, s.id ]},{:include_blank => '-Choose-'}, :class=>"form-control w-100"%>
                <%=f.error_span(:parent_id) %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.label :meta_description, :class => 'control-label' %>
                <%= f.text_area :meta_description, :class => 'form-control',:ckeditor => {:removePlugins => 'forms,about,flash',:removeButtons => 'Image', :height => '300px'} %>
                <%=f.error_span(:meta_description) %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col text-center">
              <div class="form-group">
                <%= f.submit nil, :class => 'btn btn-success' %>
                <%= link_to t('.cancel', :default => t("helpers.links.cancel")), categories_path, :class => 'btn btn-light' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<script type="text/javascript">
  $(".select2").select2();
  $("input[type='checkbox'], input[type='radio']").bootstrapSwitch();
</script>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= categories_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <%= link_to t('.new', :default => t("helpers.links.new")),new_category_path,:class => 'btn btn-success mb-2' %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th class="text-center"><%= model_class.human_attribute_name(:id) %></th>
                <th class="text-center"><%= model_class.human_attribute_name(:title) %></th>
                <th class="text-center"><%= model_class.human_attribute_name(:parent_id) %></th>
                <th class="text-center"><%= model_class.human_attribute_name(:created_at) %></th>
                <th class="text-center"><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @categories.each do |category| %>
              <tr>
                <td class="text-center"><%= link_to category.id, category_path(category) %></td>
                <td class="text-center"><%= category.title.upcase %></td>
                <td class="text-center"><%= category.parent.title.upcase rescue "-" %></td>
                <td class="text-center"><%= category.created_at.strftime("%B %d, %Y %H:%M") %></td>
                <td class="text-center">
                  <%= link_to t('.show', :default => t("helpers.links.show")),
                  category_path(category), :class => 'btn btn-default btn-xs' %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_category_path(category), :class => 'btn btn-warning btn-xs' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  category_path(category),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-xs btn-danger' %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $('.table').DataTable();
  } );
</script>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item">
              <a href="<%= categories_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/categories/show.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @category.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:meta_description) %>:</strong></dt>
  <dd><%= @category.meta_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:slug) %>:</strong></dt>
  <dd><%= @category.slug %></dd>
  <dt><strong><%= model_class.human_attribute_name(:parent_id) %>:</strong></dt>
  <dd><%= @category.parent_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              categories_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_category_path(@category), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              category_path(@category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>